services:

  postgres:
    container_name: db
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
  
  fastapi:
    container_name: backend
    build: .
    command: uvicorn --host 0.0.0.0 --port 8080 app.main:app --reload
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  database-data: