"""add referal_code_expiration

Revision ID: b58ee3d641e1
Revises: f7d78f5ec336
Create Date: 2024-02-16 09:37:39.296082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58ee3d641e1'
down_revision: Union[str, None] = 'f7d78f5ec336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_code_expiration')
    # ### end Alembic commands ###
