"""Add referal

Revision ID: f7d78f5ec336
Revises: e8767bc2eae7
Create Date: 2024-02-15 17:25:47.616840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d78f5ec336'
down_revision: Union[str, None] = 'e8767bc2eae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referal_code', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('referal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referal_id')
    op.drop_column('users', 'referal_code')
    # ### end Alembic commands ###
